# Generated by Django 3.2.25 on 2024-12-08 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caveapp', '0002_contacts_alter_booking_date_check_out'),
    ]

    operations = [
    ]
